adding

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -36,15 +36,26 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
-    - name: Setup kubectl
+    - name: Set up kubectl
       uses: azure/setup-kubectl@v1
       with:
         version: 'latest'
+
     - name: Create .kube directory
       run: mkdir -p $HOME/.kube
-    
+
     - name: Configure Kubeconfig
       run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
+      continue-on-error: true
+
+    - name: Verify kubeconfig
+      run: |
+        if [ -f $HOME/.kube/config ]; then
+          echo "Kubeconfig successfully created"
+        else
+          echo "Kubeconfig creation failed"
+          exit 1
+        fi
 
     - name: Deploy to Kubernetes
       run: |
